// Copyright (c) Meta Platforms, Inc. and affiliates.
// Seed data for AndojoFly flight booking app

// Airlines
export const airlines = [
  {
    id: 'airline_1',
    name: 'American Airlines',
    iata_code: 'AA',
    icao_code: 'AAL',
    country: 'USA',
    logo_url: 'https://images.kiwi.com/airlines/64/AA.png',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'airline_2',
    name: 'Delta Air Lines',
    iata_code: 'DL',
    icao_code: 'DAL',
    country: 'USA',
    logo_url: 'https://images.kiwi.com/airlines/64/DL.png',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'airline_3',
    name: 'United Airlines',
    iata_code: 'UA',
    icao_code: 'UAL',
    country: 'USA',
    logo_url: 'https://images.kiwi.com/airlines/64/UA.png',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'airline_4',
    name: 'Southwest Airlines',
    iata_code: 'WN',
    icao_code: 'SWA',
    country: 'USA',
    logo_url: 'https://images.kiwi.com/airlines/64/WN.png',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'airline_5',
    name: 'JetBlue Airways',
    iata_code: 'B6',
    icao_code: 'JBU',
    country: 'USA',
    logo_url: 'https://images.kiwi.com/airlines/64/B6.png',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]

// Airports
export const airports = [
  {
    code: 'JFK',
    name: 'John F. Kennedy International Airport',
    city: 'New York',
    country: 'USA',
    timezone: 'America/New_York',
    latitude: 40.6413,
    longitude: -73.7781,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    code: 'LAX',
    name: 'Los Angeles International Airport',
    city: 'Los Angeles',
    country: 'USA',
    timezone: 'America/Los_Angeles',
    latitude: 33.9416,
    longitude: -118.4085,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    code: 'ORD',
    name: "O'Hare International Airport",
    city: 'Chicago',
    country: 'USA',
    timezone: 'America/Chicago',
    latitude: 41.9742,
    longitude: -87.9073,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    code: 'SFO',
    name: 'San Francisco International Airport',
    city: 'San Francisco',
    country: 'USA',
    timezone: 'America/Los_Angeles',
    latitude: 37.6213,
    longitude: -122.379,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    code: 'MIA',
    name: 'Miami International Airport',
    city: 'Miami',
    country: 'USA',
    timezone: 'America/New_York',
    latitude: 25.7959,
    longitude: -80.287,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    code: 'SEA',
    name: 'Seattle-Tacoma International Airport',
    city: 'Seattle',
    country: 'USA',
    timezone: 'America/Los_Angeles',
    latitude: 47.4502,
    longitude: -122.3088,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    code: 'DFW',
    name: 'Dallas/Fort Worth International Airport',
    city: 'Dallas',
    country: 'USA',
    timezone: 'America/Chicago',
    latitude: 32.8998,
    longitude: -97.0403,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    code: 'ATL',
    name: 'Hartsfield-Jackson Atlanta International Airport',
    city: 'Atlanta',
    country: 'USA',
    timezone: 'America/New_York',
    latitude: 33.6407,
    longitude: -84.4277,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]

// Aircraft Types
export const aircraftTypes = [
  {
    id: 'aircraft_1',
    name: 'Boeing 737-800',
    manufacturer: 'Boeing',
    iata_code: '738',
    capacity: 189,
    range_km: 5765,
    cruise_speed_kmh: 842,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'aircraft_2',
    name: 'Airbus A320',
    manufacturer: 'Airbus',
    iata_code: '320',
    capacity: 180,
    range_km: 6150,
    cruise_speed_kmh: 840,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'aircraft_3',
    name: 'Boeing 777-300ER',
    manufacturer: 'Boeing',
    iata_code: '77W',
    capacity: 396,
    range_km: 13649,
    cruise_speed_kmh: 905,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'aircraft_4',
    name: 'Airbus A350-900',
    manufacturer: 'Airbus',
    iata_code: '359',
    capacity: 325,
    range_km: 15000,
    cruise_speed_kmh: 910,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'aircraft_5',
    name: 'Boeing 787-9 Dreamliner',
    manufacturer: 'Boeing',
    iata_code: '789',
    capacity: 296,
    range_km: 14140,
    cruise_speed_kmh: 913,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]

// Cabin Classes
export const cabinClasses = [
  {
    id: 'class_1',
    name: 'Economy',
    code: 'economy',
    description: 'Standard seating with basic amenities',
    price_multiplier: 1.0,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'class_2',
    name: 'Premium Economy',
    code: 'premium_economy',
    description: 'Extra legroom and enhanced amenities',
    price_multiplier: 1.5,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'class_3',
    name: 'Business',
    code: 'business',
    description: 'Lie-flat seats, premium dining, and lounge access',
    price_multiplier: 3.0,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'class_4',
    name: 'First Class',
    code: 'first',
    description: 'Ultimate luxury with private suites',
    price_multiplier: 5.0,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]

// Sample Bookings
export const sampleBookings = [
  {
    id: 'booking_1',
    user_id: 1,
    booking_reference: 'ABCD123',
    status: 'confirmed',
    total_price: 450.0,
    currency: 'USD',
    passengers: 1,
    created_at: '2024-01-15T10:30:00.000Z',
    updated_at: '2024-01-15T10:30:00.000Z',
  },
  {
    id: 'booking_2',
    user_id: 2,
    booking_reference: 'EFGH456',
    status: 'confirmed',
    total_price: 1200.0,
    currency: 'USD',
    passengers: 2,
    created_at: '2024-01-20T14:45:00.000Z',
    updated_at: '2024-01-20T14:45:00.000Z',
  },
]

// Passengers
export const samplePassengers = [
  {
    id: 'passenger_1',
    user_id: 1,
    first_name: 'John',
    last_name: 'Doe',
    date_of_birth: '1985-03-15',
    passport_number: 'US123456789',
    passport_expiry: '2030-03-15',
    nationality: 'USA',
    is_primary: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'passenger_2',
    user_id: 2,
    first_name: 'Sarah',
    last_name: 'Smith',
    date_of_birth: '1990-06-20',
    passport_number: 'US987654321',
    passport_expiry: '2029-06-20',
    nationality: 'USA',
    is_primary: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]

// Popular Routes
export const popularRoutes = [
  { origin: 'JFK', destination: 'LAX', popularity_score: 100 },
  { origin: 'LAX', destination: 'JFK', popularity_score: 100 },
  { origin: 'ORD', destination: 'LAX', popularity_score: 95 },
  { origin: 'JFK', destination: 'MIA', popularity_score: 90 },
  { origin: 'SFO', destination: 'JFK', popularity_score: 88 },
  { origin: 'LAX', destination: 'SEA', popularity_score: 85 },
  { origin: 'DFW', destination: 'ATL', popularity_score: 82 },
  { origin: 'ORD', destination: 'SFO', popularity_score: 80 },
]
