// Copyright (c) Meta Platforms, Inc. and affiliates.
import { StyleSheet } from 'react-native'
import { colors, metrics } from '@andojo/shared-theme'
export const styles = StyleSheet.create({
  screen: {
    backgroundColor: colors.background,
    flex: 1,
  },
  container: {
    backgroundColor: colors.background,
    flex: 1,
  },
  contentContainer: {
    flexGrow: 1,
    padding: metrics.medium,
  },
  title: {
    color: colors.text,
    fontSize: 24,
    fontWeight: '600',
    marginBottom: metrics.large,
    textAlign: 'center',
  },
  // Amount screen styles
  amountCard: {
    backgroundColor: colors.palette.neutral100,
    borderRadius: metrics.borderRadiusLarge,
    elevation: 5,
    marginBottom: metrics.xl,
    padding: metrics.large,
    shadowColor: colors.palette.neutral900,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
  },
  amountInputContainer: {
    alignItems: 'center',
    width: '100%',
  },
  amountInputWrapper: {
    alignItems: 'center',
  },
  amountRow: {
    alignItems: 'center',
    flexDirection: 'row',
    height: 80,
    justifyContent: 'center',
  },
  currencyContainer: {
    alignItems: 'flex-end',
    justifyContent: 'center',
    marginRight: 10,
    width: 40,
  },
  currencySymbol: {
    color: colors.text,
    fontSize: 48,
    fontWeight: '500',
    includeFontPadding: false,
    justifyContent: 'center',
    lineHeight: 72,
    textAlignVertical: 'center',
  },
  currencySymbolPlaceholder: {
    color: colors.palette.neutral400,
  },
  amountInput: {
    color: colors.text,
    fontSize: 48,
    fontWeight: '600',
    height: 60,
    includeFontPadding: false,
    minWidth: 200,
    paddingBottom: 0,
    paddingTop: 0,
    textAlign: 'left',
    textAlignVertical: 'center',
  },
  amountInputPlaceholder: {
    color: colors.palette.neutral400,
  },
  textFieldContainer: {
    backgroundColor: 'transparent',
    height: 72,
    minWidth: '70%',
  },
  amountUnderline: {
    backgroundColor: colors.palette.neutral400,
    height: 2,
    marginTop: metrics.tiny,
    width: '100%',
  },
  amountUnderlineActive: {
    backgroundColor: colors.palette.primary400,
    height: 3,
  },
  quickAmountsContainer: {
    gap: metrics.medium,
    marginBottom: metrics.xl,
  },
  quickAmountsRow: {
    flexDirection: 'row',
    gap: metrics.small,
    paddingHorizontal: metrics.small,
    paddingVertical: metrics.tiny,
  },
  quickAmountButton: {
    backgroundColor: colors.palette.neutral200,
    borderRadius: metrics.borderRadiusLarge,
    elevation: 3,
    minWidth: 100,
    paddingHorizontal: metrics.medium,
    shadowColor: colors.palette.neutral900,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  quickAmountText: {
    color: colors.text,
    fontSize: 16,
    fontWeight: '600',
  },
  infoCard: {
    alignItems: 'center',
    backgroundColor: colors.palette.neutral200,
    borderRadius: metrics.borderRadiusMedium,
    elevation: 2,
    flexDirection: 'row',
    marginBottom: metrics.xl,
    padding: metrics.medium,
    shadowColor: colors.palette.neutral900,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
  },
  infoIcon: {
    marginRight: metrics.small,
  },
  infoText: {
    color: colors.textDim,
    flex: 1,
    lineHeight: 20,
  },
  // Method screen styles
  methodsContainer: {
    marginBottom: metrics.small,
  },
  methodCard: {
    backgroundColor: colors.palette.neutral200,
    borderRadius: metrics.borderRadiusLarge,
    elevation: 3,
    marginBottom: metrics.small,
    padding: metrics.medium,
    shadowColor: colors.palette.neutral900,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  selectedMethodCard: {
    backgroundColor: colors.palette.primary400,
    elevation: 5,
    shadowColor: colors.palette.primary500,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
  },
  methodIconContainer: {
    alignItems: 'center',
    backgroundColor: colors.palette.neutral100,
    borderRadius: 24,
    elevation: 2,
    height: 48,
    justifyContent: 'center',
    margin: metrics.small,
    shadowColor: colors.palette.neutral900,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    width: 48,
  },
  selectedMethodIconContainer: {
    backgroundColor: 'transparent',
  },
  checkmarkContainer: {
    alignItems: 'center',
    backgroundColor: colors.palette.primary600,
    borderRadius: 16,
    height: 32,
    justifyContent: 'center',
    margin: metrics.small,
    width: 32,
  },
  methodName: {
    color: colors.text,
    fontSize: 18,
    fontWeight: '600',
    marginBottom: metrics.tiny,
  },
  methodDescription: {
    color: colors.textDim,
    fontSize: 14,
    lineHeight: 20,
  },
  selectedMethodText: {
    color: colors.palette.neutral100,
  },
  summaryCard: {
    borderRadius: metrics.borderRadiusLarge,
    elevation: 5,
    marginBottom: metrics.xl,
    marginTop: metrics.medium,
    padding: metrics.large,
    shadowColor: colors.palette.neutral900,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
  },
  summaryContent: {
    backgroundColor: 'rgba(255, 255, 255, 0.5)',
    borderRadius: metrics.borderRadiusMedium,
    marginTop: metrics.medium,
    padding: metrics.medium,
  },
  summaryTitle: {
    color: colors.text,
    fontSize: 20,
    fontWeight: '600',
    marginBottom: metrics.small,
    textAlign: 'center',
  },
  summaryRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: metrics.small,
  },
  summaryLabel: {
    color: colors.textDim,
    fontSize: 16,
  },
  summaryValue: {
    color: colors.text,
    fontSize: 16,
    fontWeight: '500',
  },
  totalLabel: {
    color: colors.text,
    fontSize: 18,
    fontWeight: '600',
  },
  totalValue: {
    color: colors.palette.primary400,
    fontSize: 18,
    fontWeight: '700',
  },
  divider: {
    backgroundColor: colors.palette.neutral400,
    height: 1,
    marginVertical: metrics.medium,
    opacity: 0.2,
  },
  // PIN screen styles
  pinCard: {
    backgroundColor: 'transparent',
    borderRadius: metrics.borderRadiusLarge,
    elevation: 4,
    marginBottom: metrics.xl,
    overflow: 'hidden',
    padding: metrics.large,
    shadowColor: colors.palette.neutral900,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
  },
  pinContainer: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    marginVertical: metrics.large,
    padding: metrics.medium,
  },
  pinInputContainer: {
    alignItems: 'center',
    backgroundColor: colors.palette.neutral100,
    borderRadius: metrics.borderRadiusLarge,
    padding: metrics.large,
    shadowColor: colors.palette.neutral900,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    width: '100%',
  },
  pinDigit: {
    alignItems: 'center',
    borderColor: colors.palette.neutral300,
    borderRadius: metrics.borderRadiusMedium,
    borderWidth: 2,
    elevation: 2,
    height: 60,
    justifyContent: 'center',
    marginHorizontal: metrics.small,
    shadowColor: colors.palette.neutral900,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    width: 60,
  },
  pinDigitFilled: {
    backgroundColor: colors.palette.primary400,
    borderColor: colors.palette.primary400,
    elevation: 4,
    shadowColor: colors.palette.primary400,
    shadowOpacity: 0.2,
  },
  pinDigitActive: {
    borderColor: colors.palette.primary500,
    elevation: 6,
    shadowColor: colors.palette.primary500,
    shadowOpacity: 0.3,
  },
  pinDot: {
    backgroundColor: colors.palette.neutral100,
    borderRadius: 8,
    elevation: 2,
    height: 16,
    shadowColor: colors.palette.neutral900,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    width: 16,
  },
  hiddenPinInput: {
    height: '100%',
    opacity: 0,
    position: 'absolute',
    width: '100%',
  },
  pinDescription: {
    color: colors.textDim,
    fontSize: 14,
    lineHeight: 20,
    marginTop: metrics.large,
    textAlign: 'center',
  },
  // Common button styles
  buttonContainer: {
    backgroundColor: colors.background,
    flexDirection: 'row',
    gap: metrics.medium,
    padding: metrics.medium,
  },
  backButtonGradient: {
    borderRadius: metrics.borderRadiusLarge,
    elevation: 4,
    flex: 1,
    overflow: 'hidden',
    shadowColor: colors.palette.neutral100,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
  },
  backButton: {
    backgroundColor: 'transparent',
    borderRadius: metrics.borderRadiusLarge,
    minHeight: 56,
    paddingVertical: metrics.medium,
  },
  backButtonIcon: {
    alignItems: 'center',
    borderRadius: 16,
    elevation: 2,
    height: 32,
    justifyContent: 'center',
    marginRight: metrics.small,
    overflow: 'hidden',
    shadowColor: colors.palette.neutral900,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    width: 32,
  },
  backButtonText: {
    color: colors.palette.neutral100,
    fontSize: 16,
    fontWeight: '600',
    textShadowColor: 'rgba(0, 0, 0, 0.2)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  continueButtonGradient: {
    borderRadius: metrics.borderRadiusLarge,
    elevation: 5,
    flex: 2,
    shadowColor: colors.palette.primary500,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
  },
  continueButton: {
    backgroundColor: 'transparent',
    borderRadius: metrics.borderRadiusLarge,
    minHeight: 56,
    paddingVertical: metrics.medium,
  },
  continueButtonText: {
    color: colors.palette.neutral100,
    fontSize: 18,
    fontWeight: '600',
    textShadowColor: 'rgba(0, 0, 0, 0.1)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  continueButtonIcon: {
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    borderRadius: 16,
    height: 32,
    justifyContent: 'center',
    marginLeft: metrics.small,
    width: 32,
  },
  disabledButton: {
    opacity: 0.6,
  },
})
