// Copyright (c) Meta Platforms, Inc. and affiliates.
// Seed data for Andojo device types
export const andojoDeviceTypes = [
  // 🔆 Lighting Devices
  {
    name: 'Andojo Glow',
    category: 'lighting',
    subcategory: 'smart_bulbs',
    capabilities: JSON.stringify({
      on_off: true,
      brightness: true,
      color_temperature: true,
      rgb_colors: true,
      scheduling: true,
    }),
    icon: 'bulb',
    brand: 'Andojo',
    model: 'GLOW-001',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Andojo Beam',
    category: 'lighting',
    subcategory: 'smart_bulbs',
    capabilities: JSON.stringify({
      on_off: true,
      brightness: true,
      color_temperature: true,
      rgb_colors: true,
      scheduling: true,
      voice_assistant: true,
    }),
    icon: 'bulb',
    brand: 'Andojo',
    model: 'BEAM-001',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Andojo Aura',
    category: 'lighting',
    subcategory: 'smart_bulbs',
    capabilities: JSON.stringify({
      on_off: true,
      brightness: true,
      color_temperature: true,
      rgb_colors: true,
      scheduling: true,
      music_sync: true,
    }),
    icon: 'bulb',
    brand: 'Andojo',
    model: 'AURA-001',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Andojo Switch',
    category: 'lighting',
    subcategory: 'smart_switches',
    capabilities: JSON.stringify({
      on_off: true,
      scheduling: true,
      energy_monitoring: true,
    }),
    icon: 'switch',
    brand: 'Andojo',
    model: 'SWITCH-001',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Andojo Click',
    category: 'lighting',
    subcategory: 'smart_switches',
    capabilities: JSON.stringify({
      on_off: true,
      brightness: true,
      scheduling: true,
      energy_monitoring: true,
    }),
    icon: 'switch',
    brand: 'Andojo',
    model: 'CLICK-001',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Andojo Volt',
    category: 'lighting',
    subcategory: 'smart_switches',
    capabilities: JSON.stringify({
      on_off: true,
      brightness: true,
      scheduling: true,
      energy_monitoring: true,
      voice_assistant: true,
    }),
    icon: 'switch',
    brand: 'Andojo',
    model: 'VOLT-001',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Andojo Plug',
    category: 'lighting',
    subcategory: 'smart_plugs',
    capabilities: JSON.stringify({
      on_off: true,
      scheduling: true,
      energy_monitoring: true,
    }),
    icon: 'plug',
    brand: 'Andojo',
    model: 'PLUG-001',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Andojo Node',
    category: 'lighting',
    subcategory: 'smart_plugs',
    capabilities: JSON.stringify({
      on_off: true,
      scheduling: true,
      energy_monitoring: true,
    }),
    icon: 'plug',
    brand: 'Andojo',
    model: 'NODE-001',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Andojo Pulse',
    category: 'lighting',
    subcategory: 'smart_plugs',
    capabilities: JSON.stringify({
      on_off: true,
      scheduling: true,
      energy_monitoring: true,
      voice_assistant: true,
    }),
    icon: 'plug',
    brand: 'Andojo',
    model: 'PULSE-001',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Andojo Strip',
    category: 'lighting',
    subcategory: 'led_strips',
    capabilities: JSON.stringify({
      on_off: true,
      brightness: true,
      rgb_colors: true,
      effects: true,
      music_sync: true,
    }),
    icon: 'strip',
    brand: 'Andojo',
    model: 'STRIP-001',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Andojo Linea',
    category: 'lighting',
    subcategory: 'led_strips',
    capabilities: JSON.stringify({
      on_off: true,
      brightness: true,
      rgb_colors: true,
      effects: true,
      music_sync: true,
      voice_assistant: true,
    }),
    icon: 'strip',
    brand: 'Andojo',
    model: 'LINEA-001',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Andojo Flux',
    category: 'lighting',
    subcategory: 'led_strips',
    capabilities: JSON.stringify({
      on_off: true,
      brightness: true,
      rgb_colors: true,
      effects: true,
      music_sync: true,
      voice_assistant: true,
    }),
    icon: 'strip',
    brand: 'Andojo',
    model: 'FLUX-001',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // 🌡️ Temperature Control
  {
    name: 'Andojo Chill',
    category: 'temperature',
    subcategory: 'smart_ac',
    capabilities: JSON.stringify({
      on_off: true,
      temperature_control: true,
      mode_selection: true,
      fan_speed: true,
      scheduling: true,
      energy_monitoring: true,
    }),
    icon: 'ac',
    brand: 'Andojo',
    model: 'CHILL-001',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Andojo Breeze',
    category: 'temperature',
    subcategory: 'smart_ac',
    capabilities: JSON.stringify({
      on_off: true,
      temperature_control: true,
      mode_selection: true,
      fan_speed: true,
      scheduling: true,
      energy_monitoring: true,
      voice_assistant: true,
    }),
    icon: 'ac',
    brand: 'Andojo',
    model: 'BREEZE-001',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Andojo Air',
    category: 'temperature',
    subcategory: 'smart_ac',
    capabilities: JSON.stringify({
      on_off: true,
      temperature_control: true,
      mode_selection: true,
      fan_speed: true,
      scheduling: true,
      energy_monitoring: true,
      voice_assistant: true,
    }),
    icon: 'ac',
    brand: 'Andojo',
    model: 'AIR-001',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Andojo Whirl',
    category: 'temperature',
    subcategory: 'smart_fans',
    capabilities: JSON.stringify({
      on_off: true,
      fan_speed: true,
      oscillation: true,
      scheduling: true,
    }),
    icon: 'fan',
    brand: 'Andojo',
    model: 'WHIRL-001',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Andojo Spin',
    category: 'temperature',
    subcategory: 'smart_fans',
    capabilities: JSON.stringify({
      on_off: true,
      fan_speed: true,
      oscillation: true,
      scheduling: true,
      voice_assistant: true,
    }),
    icon: 'fan',
    brand: 'Andojo',
    model: 'SPIN-001',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Andojo Zephyr',
    category: 'temperature',
    subcategory: 'smart_fans',
    capabilities: JSON.stringify({
      on_off: true,
      fan_speed: true,
      oscillation: true,
      scheduling: true,
      voice_assistant: true,
    }),
    icon: 'fan',
    brand: 'Andojo',
    model: 'ZEPHYR-001',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Andojo Warm',
    category: 'temperature',
    subcategory: 'smart_heaters',
    capabilities: JSON.stringify({
      on_off: true,
      temperature_control: true,
      scheduling: true,
      energy_monitoring: true,
    }),
    icon: 'heater',
    brand: 'Andojo',
    model: 'WARM-001',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Andojo Heat',
    category: 'temperature',
    subcategory: 'smart_heaters',
    capabilities: JSON.stringify({
      on_off: true,
      temperature_control: true,
      scheduling: true,
      energy_monitoring: true,
      voice_assistant: true,
    }),
    icon: 'heater',
    brand: 'Andojo',
    model: 'HEAT-001',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Andojo Ember',
    category: 'temperature',
    subcategory: 'smart_heaters',
    capabilities: JSON.stringify({
      on_off: true,
      temperature_control: true,
      scheduling: true,
      energy_monitoring: true,
      voice_assistant: true,
    }),
    icon: 'heater',
    brand: 'Andojo',
    model: 'EMBER-001',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // 🔒 Security & Surveillance
  {
    name: 'Andojo Cam',
    category: 'security',
    subcategory: 'security_cameras',
    capabilities: JSON.stringify({
      on_off: true,
      motion_detection: true,
      night_vision: true,
      two_way_audio: true,
      recording: true,
      cloud_storage: true,
    }),
    icon: 'camera',
    brand: 'Andojo',
    model: 'CAM-001',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Andojo Watch',
    category: 'security',
    subcategory: 'security_cameras',
    capabilities: JSON.stringify({
      on_off: true,
      motion_detection: true,
      night_vision: true,
      two_way_audio: true,
      recording: true,
      cloud_storage: true,
    }),
    icon: 'camera',
    brand: 'Andojo',
    model: 'WATCH-001',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Andojo Vision',
    category: 'security',
    subcategory: 'security_cameras',
    capabilities: JSON.stringify({
      on_off: true,
      motion_detection: true,
      night_vision: true,
      two_way_audio: true,
      recording: true,
      cloud_storage: true,
    }),
    icon: 'camera',
    brand: 'Andojo',
    model: 'VISION-001',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Andojo Sense',
    category: 'security',
    subcategory: 'door_sensors',
    capabilities: JSON.stringify({
      motion_detection: true,
    }),
    icon: 'sensor',
    brand: 'Andojo',
    model: 'SENSE-001',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Andojo Entry',
    category: 'security',
    subcategory: 'door_sensors',
    capabilities: JSON.stringify({
      motion_detection: true,
    }),
    icon: 'sensor',
    brand: 'Andojo',
    model: 'ENTRY-001',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Andojo Frame',
    category: 'security',
    subcategory: 'door_sensors',
    capabilities: JSON.stringify({
      motion_detection: true,
    }),
    icon: 'sensor',
    brand: 'Andojo',
    model: 'FRAME-001',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // 🔊 Smart Audio Devices
  {
    name: 'Andojo Echo',
    category: 'audio',
    subcategory: 'smart_audio',
    capabilities: JSON.stringify({
      on_off: true,
      volume_control: true,
      music_playback: true,
      voice_assistant: true,
      bluetooth: true,
    }),
    icon: 'speaker',
    brand: 'Andojo',
    model: 'ECHO-001',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Andojo Voice',
    category: 'audio',
    subcategory: 'smart_audio',
    capabilities: JSON.stringify({
      on_off: true,
      volume_control: true,
      music_playback: true,
      voice_assistant: true,
      bluetooth: true,
    }),
    icon: 'speaker',
    brand: 'Andojo',
    model: 'VOICE-001',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Andojo Tune',
    category: 'audio',
    subcategory: 'smart_audio',
    capabilities: JSON.stringify({
      on_off: true,
      volume_control: true,
      music_playback: true,
      voice_assistant: true,
      bluetooth: true,
    }),
    icon: 'speaker',
    brand: 'Andojo',
    model: 'TUNE-001',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Andojo Bar',
    category: 'audio',
    subcategory: 'smart_audio',
    capabilities: JSON.stringify({
      on_off: true,
      volume_control: true,
      music_playback: true,
      bluetooth: true,
    }),
    icon: 'soundbar',
    brand: 'Andojo',
    model: 'BAR-001',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Andojo Sound',
    category: 'audio',
    subcategory: 'smart_audio',
    capabilities: JSON.stringify({
      on_off: true,
      volume_control: true,
      music_playback: true,
      bluetooth: true,
    }),
    icon: 'soundbar',
    brand: 'Andojo',
    model: 'SOUND-001',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Andojo Wave',
    category: 'audio',
    subcategory: 'smart_audio',
    capabilities: JSON.stringify({
      on_off: true,
      volume_control: true,
      music_playback: true,
      bluetooth: true,
    }),
    icon: 'soundbar',
    brand: 'Andojo',
    model: 'WAVE-001',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
]
