#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

if [ -f package-lock.json ]; then
  echo "❌ package-lock.json found. Please use only yarn.lock for dependency management." >&2
  exit 1
fi

yarn lint-staged
